# Generated by Django 3.0.1 on 2020-02-27 16:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('date_create', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HighLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=225)),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('specifications', models.ManyToManyField(to='watches.Specification')),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('price_before_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categorize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.Categorize')),
                ('highlight', models.ManyToManyField(blank=True, to='watches.HighLight')),
                ('specifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watches.Specifications')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.Watches')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
