# Generated by Django 3.0.1 on 2020-02-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_auto_20200227_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='categorize',
        ),
        migrations.RemoveField(
            model_name='watches',
            name='highlight',
        ),
    ]
