# Generated by Django 3.0.1 on 2020-02-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_auto_20200228_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watches',
            name='specifications',
        ),
    ]
