# Generated by Django 3.0.1 on 2020-02-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_remove_watches_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='categorize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watches.Categorize'),
        ),
        migrations.AddField(
            model_name='watches',
            name='highlight',
            field=models.ManyToManyField(blank=True, to='watches.HighLight'),
        ),
        migrations.AddField(
            model_name='watches',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watches.Specifications'),
        ),
    ]
