# Generated by Django 3.0.1 on 2020-02-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_auto_20200228_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='price_before_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
