# Generated by Django 3.0.1 on 2020-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_auto_20200228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='watches.Specification'),
        ),
    ]
