# Generated by Django 3.0.1 on 2020-03-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0009_auto_20200229_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
    ]
