# Generated by Django 3.0.1 on 2020-03-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0011_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
    ]
