# Generated by Django 3.0.1 on 2020-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0015_auto_20200303_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
    ]
